create database if not exists LABORATORIO;
grant all privileges on LABORATORIO.* to 'Tester'@'%';
use LABORATORIO;
CREATE TABLE IF NOT EXISTS EXAMES (
	PEDIDO INT NOT NULL,
	PACMATR CHAR(8) NOT NULL,
	SOLCRM CHAR(5) NOT NULL,
	CONVENIO CHAR(3) DEFAULT '000',
	LAUDO VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (PEDIDO)
);